import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {TiSocialLinkedin, TiSocialTwitter, TiSocialYoutube, TiSocialInstagram, TiSocialGithub} from 'react-icons/ti'
import {BsBehance, BsGithub} from 'react-icons/bs'
import {AiFillInstagram} from 'react-icons/ai'
import { Card, Row, Button } from "@nextui-org/react";
import { Collapse, Col, Text, Grid, Badge, Avatar, Link, Switch } from "@nextui-org/react";


export default function Home() {
  return (
    < div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-5 dark:bg-black'>
        <section className='max-h-screen mt-10  '>
          <nav className='flex justify-between'>
          <Switch />
          <BsFillMoonStarsFill className='md:cursor-pointer sm:cursor-pointer z-10'/>
          </nav>

      
          <div className='flex justify-center -mt-24'>
          <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
          <lottie-player src="https://assets7.lottiefiles.com/packages/lf20_aesgckiv.json"  background="transparent"  speed="1"  style={{width: 500, height: 500}}  loop  autoplay></lottie-player>
          </div>
          <div className='text-center -mt-20'>
            <h3 className='text-1xl md:text-4xl'>Hey There!</h3>
            <div className='flex justify-center'>
              <Text
              color="black"
              h1
              size={30}
              weight="bold"
               >
               I am
            </Text>
            <Text
              className='ml-3'
              h1
              size={30}
              css={{
                textGradient: "45deg, $blue600 -20%, $yellow600 50%",
              }}
              weight="bold"
               >
               AK Deepankar.
            </Text>
            </div>
            <h3 className='text-gray-800 md:text-2xl md:pt-5 max-w-xl mx-auto'>Student, who is either busy <em>Experimenting</em>  <br></br> or <em>Pondering</em> over the <em className='bg-green-100'>Next Big Idea.</em></h3>
          </div>

          <div className='flex justify-center pt-5'>
          <Grid>
          <Card>
           <Card.Body>
            <Row className='flex justify-between'>
          <TiSocialLinkedin className='cursor-pointer text-2xl ml-5'/>
          <TiSocialTwitter className='cursor-pointer text-2xl ml-5'/>
          <TiSocialYoutube className='cursor-pointer text-2xl ml-5'/>
          <AiFillInstagram className='cursor-pointer text-2xl ml-5'/>
          <BsBehance className='cursor-pointer text-2xl ml-5'/>
          <BsGithub className='cursor-pointer text-2xl ml-5 mr-5'/>
            </Row>
           
           </Card.Body>
          </Card>
          </Grid>
          </div>
          
    </section>


<section className='pt-5 flex justify-center md:text-2xl md:pt-5 max-w-xl mx-auto'>
              <Grid>
            <Card>
              <Card.Header className='flex justify-between'>
                <div>
                <h1 className='text-3xl text-black-600 pt-5 font-bold -mt-4 '>Skills</h1>
                </div>
                <div className='-mt-2 ml-2'>
              <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
              <lottie-player src="https://assets1.lottiefiles.com/packages/lf20_ht8zw3es.json"  background="transparent"  speed="1"  style={{width: 50, height: 50}}  loop  autoplay></lottie-player>
              </div>
              </Card.Header>
              <Card.Divider />
              <Card.Body css={{ py: "$10" }}>
                <div>
                <h1 className='pl-3 pb-2'>Programming / Frameworks / Libraries / Tools</h1>
                <Grid.Container gap={1}>
          <Grid>
            <Badge variant="flat">HTML</Badge>
          </Grid>
          <Grid>
            <Badge variant="flat">CSS</Badge>
          </Grid>
          <Grid>
            <Badge variant="flat">JavaScript</Badge>
          </Grid>
          <Grid>
            <Badge color="primary" variant="flat">
              BootStrap
            </Badge>
          </Grid>
          <Grid>
            <Badge color="primary" variant="flat">
              Tailwind CSS
            </Badge>
          </Grid>
          <Grid>
            <Badge color="primary" variant="flat">
              React
            </Badge>
          </Grid>
          <Grid>
            <Badge color="primary" variant="flat">
              NextJs
            </Badge>
          </Grid>
          <Grid>
            <Badge color="secondary" variant="flat">
              Flask
            </Badge>
          </Grid>
          <Grid>
            <Badge color="secondary" variant="flat">
              Django
            </Badge>
          </Grid>
          <Grid>
            <Badge color="success" variant="flat">
              C
            </Badge>
          </Grid>
          <Grid>
            <Badge color="success" variant="flat">
              Python
            </Badge>
          </Grid>
          <Grid>
            <Badge color="success" variant="flat">
              Java
            </Badge>
          </Grid>
          <Grid>
            <Badge color="warning" variant="flat">
              Matplotlib
            </Badge>
          </Grid>
          <Grid>
            <Badge color="error" variant="flat">
              VS Code
            </Badge>
          </Grid>
          <Grid>
            <Badge color="error" variant="flat">
              Github
            </Badge>
          </Grid>
        </Grid.Container>

        <h1 className='pl-3 pt-2'>Design - Graphic / UI UX</h1>
        <div className='flex justify-between pl-2 pr-2 pt-2'>
          <Avatar
          size="lg"
          src="ps.svg"
          bordered
          squared
        />
        <Avatar
          size="lg"
          src="illustrator.svg"
          bordered
          squared
        />
        <Avatar
          size="lg"
          src="fresco.svg"
          bordered
          squared
        />
        <Avatar
          size="lg"
          src="xd.svg"
          bordered
          squared
        />
        <Avatar
          size="lg"
          src="lightroom.svg"
          bordered
          squared
        />
        <Avatar
          size="lg"
          src="animate.svg"
          bordered
          squared
        />
        </div>
        </div>
        </Card.Body>
        </Card>
        </Grid>
</section>

<section className='mt-3 flex justify-center md:text-2xl md:pt-5 max-w-xl mx-auto' >
<Grid>
        <Card>
        <Card.Header className='flex justify-between'>
                <div>
                <h1 className='text-3xl text-black-600 pt-5 font-bold -mt-4 '>Projects</h1>
                </div>
                <div className='-mt-2 ml-2'>
              <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
              <lottie-player src="https://assets2.lottiefiles.com/packages/lf20_hylaaytn.json"  background="transparent"  speed="1"  style={{width: 50, height: 50}}  loop  autoplay></lottie-player>
              </div>
              </Card.Header>
          <Card.Divider />
          <Card.Body css={{ py: "$10" }}>
            <div>
            <Card css={{ w: "100%", h: "200px" }}>
    <Card.Header css={{ position: "absolute", zIndex: 1, top: 5 }}>
      <Col>
        <Text size={12} weight="bold" transform="uppercase" color="#ffffffAA">
          New
        </Text>
        <Text h3 color="white">
          PORTFOLIO
        </Text>
      </Col>
    </Card.Header>
    <Card.Body css={{ p: 0 }}>
      <Card.Image
        src="https://images.pexels.com/photos/811587/pexels-photo-811587.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        width="100%"
        height="100%"
        objectFit="cover"
        alt="Card example background"
      />
    </Card.Body>
    <Card.Footer
      isBlurred
      css={{
        position: "absolute",
        bgBlur: "#ffffff66",
        borderTop: "$borderWeights$light solid rgba(255, 255, 255, 0.2)",
        bottom: 0,
        zIndex: 1,
      }}
    >
      <Row>
        <Col>
          <Text color="#000" size={12}>
            Currently Viewing
          </Text>
         <Text color="#000" size={12}>
          Portfolio. 
          </Text> 
        </Col>
        <Col>
          <Row justify="flex-end">
            <Button flat auto rounded color="secondary">
              <Text
                css={{ color: "black" }}
                size={12}
                weight="bold"
                transform="uppercase"
              >
                NEXT Js, Tailwind CSS
              </Text>
            </Button>
          </Row>
        </Col>
      </Row>
    </Card.Footer>
  </Card>
            </div>
          </Card.Body>
        </Card>
      </Grid>


      
</section>



<section className='mt-5 flex justify-center mb-5 md:text-2xl md:pt-5 max-w-xl mx-auto'>
<Card className=' h-40'>
    <Card.Header css={{ position: "absolute", zIndex: 1, top: 5 }}>
      <Col>
        <Text className='bg-black' size={16} weight="bold" transform="uppercase" color="#ffffff">
          Teaming Up For A Project or Hackathon ?
        </Text>
        <Text className='bg-black' h4 color="white">
          Just Ping Me! Anyway I am Still Learning & Always Open to New ideas.
        </Text>
      </Col>
    </Card.Header>
    <Card.Image
      src="https://nextui.org/images/card-example-4.jpeg"
      objectFit="cover"
      width="100%"
      height="100%"
      alt="Card image background"
    />
  </Card>
</section>
<section className='flex justify-center mb-5'>
  <h2 className=' bg-blue-50 p-1 rounded'>2023 - AK DEEPANKAR</h2>
</section>
</main>
</div>
  )
}
